"""create utility type table

Revision ID: 62f966034799
Revises: 4d31b69dd7e2
Create Date: 2026-07-18 17:15:51.803978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f966034799'
down_revision = '4d31b69dd7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_area_name'), ['area_name'], unique=False)

    op.create_table('utility_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('outage_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('utility_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'VERIFIED', 'IN_PROGRESS', 'RESOLVED', name='reportstatus'), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['utility_type_id'], ['utility_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outage_reports', schema=None) as batch_op:
        batch_op.create_index('ix_hotspot_lookup', ['location_id', 'utility_type_id', 'reported_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'utility_types', ['utility_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('outage_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_hotspot_lookup')

    op.drop_table('outage_reports')
    op.drop_table('utility_types')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_area_name'))

    op.drop_table('locations')
    # ### end Alembic commands ###
